version: '3.8'

services:
    exchange_stub:
        build:
            context: ./src
            dockerfile: ExchangeStub/Dockerfile
        ports:
            - '7001:8080'
        environment:
            ASPNETCORE_URLS: http://+:8080
        networks:
            - trading-network
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8080/healthz']
            interval: 30s
            retries: 3
            start_period: 5s

    collector:
        image: mcr.microsoft.com/dotnet/runtime:8.0
        container_name: collector
        build:
            context: ./src
            dockerfile: Collector/Dockerfile
        environment:
            - EXCHANGE_WS_URL=ws://exchange_stub:8080/ws/ticker?symbol=BTCUSDT
        networks:
            - trading-network
        depends_on:
            - gateway
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:5000/healthz']
            interval: 30s
            retries: 3
            start_period: 5s

    gateway:
        image: mcr.microsoft.com/dotnet/aspnet:8.0
        container_name: gateway
        build:
            context: ./src
            dockerfile: Gateway/Dockerfile
        ports:
            - '8080:8080'
        environment:
            - ASPNETCORE_URLS=http://+:8080
        networks:
            - trading-network
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:5000/healthz']
            interval: 30s
            retries: 3
            start_period: 5s

    webui:
        build:
            context: ./webui
        container_name: webui
        ports:
            - '80:80'
        networks:
            - trading-network
        depends_on:
            - gateway
        environment:
            - REACT_APP_SIGNALR_URL=http://gateway:8080/hub/market

networks:
    trading-network:
        driver: bridge
